version: "3.7"

x-service-base: &service-base
  image: cloudreactor-ecs-quickstart-dev
  build:
    context: ./
  volumes:
    - ./src/:/home/appuser/    

services:
  task_1:
    <<: *service-base
    command: python task_1.py

  file_io:
    <<: *service-base
    command: python file_io.py
    
  web_server:
    <<: *service-base
    command: flask run -p 7070 --host=0.0.0.0
    environment:
      FLASK_APP: web_server.py
    ports:
      - "7070:7070"
      
      