name: Tests
on:
  push:
    branches: [ "master", "github-actions-ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Test with pytest
      run: |
        pytest
      env:
        PYTHONPATH: src
    - name: Type check with mypy
      run: |
        mypy src
      env:
        PYTHONPATH: src
